# worker/wrangler.toml
name = "inpinity-presale-worker"
main = "src/index.ts"
compatibility_date = "2025-08-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  # API:
  { pattern = "inpinity.online/api/token/*", zone_name = "inpinity.online" },
  # Mount Pages-Projekt auf Pfad /token:
  { pattern = "inpinity.online/token*",      zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "KV_PRESALE", id = "ac3b4c80ae9e4b77abcee11dab27f199" },
  { binding = "KV_CLAIMS",  id = "86ad86beb528411dbe6df7a7558300cf" }
]

[vars]
USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
INPI_MINT = "GBfEVjkSn3KSmRnqe83Kb8c42DsxkJmiDCb4AbNYBYt1"
CREATOR   = "GEFoNLncuhh4nH99GKvVEUxe59SGe74dbLG7UUtfHrCp"
USDC_VAULT_ATA = "8PEkHngVQJoBMk68b1R5dyXjmqe3UthutSUbAYiGcpg6"

PRESALE_STATE = "open"
PRESALE_PRICE_USDC = "0.00031415"
PUBLIC_PRICE_USDC  = "0.00034999"

# Rabatt/Caps/Bonus/NFT-Gate (werden vom Frontend gelesen)
DISCOUNT_BPS = "1000"
PRESALE_MIN_USDC = "10"
PRESALE_MAX_USDC = "1000"
AIRDROP_BONUS_BPS = "600"
GATE_NFT_MINT = "6xvwKXMUGfkqhs1f3ZN3KkrdvLh2vF3tX1pqLo9aYPrQ"

EARLY_CLAIM_ENABLED = "true"
EARLY_FLAT_USDC = "1.0"

TGE_TS = "1764003600"

ALLOWED_ORIGINS = "https://inpinity.online,https://inpi-token.pages.dev,https://*.inpi-token.pages.dev"
SOLANA_RPC = "https://api.mainnet-beta.solana.com"
PAGES_UPSTREAM = "https://inpi-token.pages.dev"