# worker/wrangler.toml
name = "inpinity-presale-worker"
main = "src/index.ts"
compatibility_date = "2025-08-25"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# WICHTIG: Nur EIN Worker darf /token bedienen
routes = [
  # API
  { pattern = "inpinity.online/api/token/*", zone_name = "inpinity.online" },
  # Pages-Projekt unter /token mounten (inkl. Unterpfade)
  { pattern = "inpinity.online/token*",      zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "KV_PRESALE", id = "ac3b4c80ae9e4b77abcee11dab27f199" },
  { binding = "KV_CLAIMS",  id = "86ad86beb528411dbe6df7a7558300cf" }
]

[vars]
# Token / Accounts
USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
INPI_MINT = "GBfEVjkSn3KSmRnqe83Kb8c42DsxkJmiDCb4AbNYBYt1"
CREATOR   = "GEFoNLncuhh4nH99GKvVEUxe59SGe74dbLG7UUtfHrCp"
USDC_VAULT_ATA = "8PEkHngVQJoBMk68b1R5dyXjmqe3UthutSUbAYiGcpg6"

# Presale / Pricing
PRESALE_STATE = "open"
PRESALE_PRICE_USDC = "0.00031415"
PUBLIC_PRICE_USDC  = "0.00034999"
DISCOUNT_BPS       = "1000"     # 10%

# Caps / Bonus / NFT-Gate
PRESALE_MIN_USDC   = "10"
PRESALE_MAX_USDC   = "1000"
AIRDROP_BONUS_BPS  = "600"
GATE_NFT_MINT      = "6xvwKXMUGfkqhs1f3ZN3KkrdvLh2vF3tX1pqLo9aYPrQ"

# Early Claim
EARLY_CLAIM_ENABLED = "true"
EARLY_FLAT_USDC     = "1.0"

# TGE (Unix Sekunden)
TGE_TS = "1764003600"

# CORS / Upstream
ALLOWED_ORIGINS = "https://inpinity.online,https://inpi-token.pages.dev,https://*.inpi-token.pages.dev"

# *** BITTE einen entdrosselten RPC nutzen (Helius/QuickNode/und Co.) ***
# Beispiel Helius:
# SOLANA_RPC = "https://mainnet.helius-rpc.com/?api-key=DEIN_HELIUS_KEY"
SOLANA_RPC   = "https://api.mainnet-beta.solana.com"

# Cloudflare Pages Projekt (Dev Domain)
PAGES_UPSTREAM = "https://inpi-token.pages.dev"