name = "inpinity-presale-worker"
main = "src/index.ts"
compatibility_date = "2025-08-28"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "inpinity.online/api/token/*", zone_name = "inpinity.online" },
  { pattern = "inpinity.online/token*",      zone_name = "inpinity.online" }
]

kv_namespaces = [
  { binding = "KV_PRESALE", id = "ac3b4c80ae9e4b77abcee11dab27f199" },
  { binding = "KV_CLAIMS",  id = "86ad86beb528411dbe6df7a7558300cf" }
]

[vars]
# Mints / Wallets
USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
INPI_MINT = "GBfEVjkSn3KSmRnqe83Kb8c42DsxkJmiDCb4AbNYBYt1"
CREATOR   = "GEFoNLncuhh4nH99GKvVEUxe59SGe74dbLG7UUtfHrCp"
USDC_VAULT_ATA = "8PEkHngVQJoBMk68b1R5dyXjmqe3UthutSUbAYiGcpg6"

# Presale (nur das Nötigste)
PRESALE_STATE = "open"
PRESALE_PRICE_USDC = "0.00031415"
DISCOUNT_BPS   = "1000"    # 10% mit Gate-NFT
GATE_NFT_MINT  = "6xvwKXMUGfkqhs1f3ZN3KkrdvLh2vF3tX1pqLo9aYPrQ"
PRESALE_MIN_USDC = "1"
PRESALE_MAX_USDC = "1000"

# (Optional) Early-Claim kannst du später reaktivieren
EARLY_CLAIM_ENABLED = "false"
EARLY_FLAT_USDC     = "1.0"

TGE_TS = "1764003600"

# RPC Failover
SOLANA_RPC = "https://mainnet.helius-rpc.com/?api-key=d95932bb-5385-4d84-ad18-7fc66e014d58,https://api.mainnet-beta.solana.com"

# CORS + Pages Upstream
ALLOWED_ORIGINS = "https://inpinity.online,https://inpi-token.pages.dev"
PAGES_UPSTREAM = "https://inpi-token.pages.dev"